# docker-compose.yml (opcional)

version: '3.8'

services:

  db-clientes:

    image: postgres:15

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      POSTGRES_DB: db_clientes

    ports:

      - "5440:5432"

    volumes:

      - pgdata:/var/lib/postgresql/data

  db-prestamos:

      image: postgres:15

      environment:

        POSTGRES_USER: postgres

        POSTGRES_PASSWORD: postgres

        POSTGRES_DB: db_prestamos

      ports:

        - "5441:5432"

      volumes:

        - pgdata:/var/lib/postgresql/data2
  db-transacciones:

    image: postgres:15

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      POSTGRES_DB: db_transacciones

    ports:

      - "5442:5432"
    volumes:

      - pgdata:/var/lib/postgresql/data3

  db-cuentas:

    image: postgres:15

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      POSTGRES_DB: db_cuentas

    ports:

      - "5443:5432"
    volumes:

      - pgdata:/var/lib/postgresql/data4

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    ports:
      - "9000:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
volumes:

  pgdata:
