spring:
  application:
    name: ServicioClientes
  datasource:
    url: jdbc:postgresql://localhost:5440/db_clientes
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    # Para cargar data.sql al inicio
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8085

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

