spring:
  application:
    name: ServicioCuentas
  datasource:
    url: jdbc:postgresql://localhost:5443/db-cuentas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    # Para cargar data.sql al inicio
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: always




server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/